from dataclasses import dataclass


@dataclass
class Python:
    keywords = [
        "and",
        "as",
        "assert",
        "break",
        "class",
        "continue",
        "def",
        "del",
        "elif",
        "else",
        "except",
        "finally",
        "for",
        "from",
        "global",
        "if",
        "import",
        "in",
        "is",
        "lambda",
        "not",
        "or",
        "pass",
        "print",
        "raise",
        "return",
        "try",
        "while",
        "with",
        "yield",
        "int",
        "str",
        "bool",
        "float",
        "list",
        "set",
        "dict",
        "abs",
        "all",
        "any",
    ]
